import type {
  Category,
  District,
  EventRecord,
  EventSubmission,
  IndoorOutdoor,
  RecurrenceType,
} from "@/lib/types";

// 데모/초기 데이터. 기준일 2026-06-10 전후로 종료·진행중·예정이 골고루 섞여 있고
// 인천 2군 9구 전역을 커버한다. 안정적인 UUID로 DB 시드/시드모드 양쪽에서 동일하게 쓴다.

const id = (n: number) =>
  `a0000000-0000-4000-8000-${String(n).padStart(12, "0")}`;

let counter = 0;
function make(e: {
  title: string;
  category: Category;
  district: District;
  startDate: string;
  endDate: string;
  venue: string;
  organizer: string;
  host: string;
  indoorOutdoor: IndoorOutdoor;
  description: string;
  createdAt: string;
  websiteUrl?: string | null;
  attachmentUrl?: string | null;
  imageUrl?: string | null;
  isFeatured?: boolean;
  recurrenceType?: RecurrenceType;
  recurrenceDays?: number[];
  likes?: number;
}): EventRecord {
  counter += 1;
  return {
    id: id(counter),
    likes: e.likes ?? 0,
    title: e.title,
    category: e.category,
    district: e.district,
    startDate: e.startDate,
    endDate: e.endDate,
    recurrenceType: e.recurrenceType ?? "none",
    recurrenceDays: e.recurrenceDays ?? [],
    venue: e.venue,
    organizer: e.organizer,
    host: e.host,
    indoorOutdoor: e.indoorOutdoor,
    description: e.description,
    websiteUrl: e.websiteUrl ?? null,
    attachmentUrl: e.attachmentUrl ?? null,
    imageUrl: e.imageUrl ?? null,
    isFeatured: e.isFeatured ?? false,
    createdAt: e.createdAt,
    updatedAt: e.createdAt,
  };
}

export const seedEvents: EventRecord[] = [
  // ── 진행중 ──
  make({
    title: "2026 송도 마이크로 페스티벌",
    category: "festival",
    district: "yeonsu",
    startDate: "2026-06-08",
    endDate: "2026-06-14",
    venue: "송도센트럴파크 일원",
    organizer: "인천광역시",
    host: "인천관광공사",
    indoorOutdoor: "outdoor",
    description:
      "송도 센트럴파크 일대에서 열리는 도심형 복합 축제. 푸드트럭, 버스킹, 야간 라이트쇼가 진행된다.",
    websiteUrl: "https://www.incheon.go.kr",
    isFeatured: true,
    likes: 18,
    createdAt: "2026-06-01T09:00:00.000Z",
  }),
  make({
    title: "부평 풍물대축제",
    category: "festival",
    district: "bupyeong",
    startDate: "2026-06-05",
    endDate: "2026-06-11",
    venue: "부평대로 차 없는 거리",
    organizer: "부평구",
    host: "부평문화원",
    indoorOutdoor: "outdoor",
    description:
      "전통 풍물패 퍼레이드와 시민 참여 난장이 어우러지는 부평의 대표 거리 축제.",
    createdAt: "2026-05-20T02:00:00.000Z",
  }),
  make({
    title: "인천국제해양포럼 2026",
    category: "expo",
    district: "yeonsu",
    startDate: "2026-06-10",
    endDate: "2026-06-12",
    venue: "송도컨벤시아",
    organizer: "인천광역시",
    host: "인천항만공사",
    indoorOutdoor: "indoor",
    description:
      "해양·물류 분야 국내외 전문가가 참여하는 국제 포럼. 세션 발표와 기업 전시가 동시에 열린다.",
    websiteUrl: "https://www.incheonport.com",
    attachmentUrl: "https://www.incheonport.com/forum/program.pdf",
    isFeatured: true,
    createdAt: "2026-05-15T01:30:00.000Z",
  }),
  make({
    title: "차이나타운 짜장면 축제",
    category: "festival",
    district: "jemulpo",
    startDate: "2026-06-09",
    endDate: "2026-06-10",
    venue: "인천 차이나타운",
    organizer: "제물포구",
    host: "차이나타운상인회",
    indoorOutdoor: "outdoor",
    description: "개항장 차이나타운에서 즐기는 짜장면·만두 등 화교 음식 문화 축제.",
    createdAt: "2026-05-25T03:00:00.000Z",
  }),
  make({
    title: "소래포구 새우 축제",
    category: "festival",
    district: "namdong",
    startDate: "2026-06-06",
    endDate: "2026-06-14",
    venue: "소래포구 종합어시장",
    organizer: "남동구",
    host: "소래포구축제위원회",
    indoorOutdoor: "outdoor",
    description: "제철 새우와 수산물을 주제로 한 남동구 대표 먹거리 축제.",
    createdAt: "2026-05-22T05:00:00.000Z",
  }),
  make({
    title: "부평 문화의거리 야시장",
    category: "etc",
    district: "bupyeong",
    startDate: "2026-06-01",
    endDate: "2026-06-30",
    venue: "부평 문화의거리",
    organizer: "부평구",
    host: "부평구상인연합회",
    indoorOutdoor: "outdoor",
    description: "한 달간 매일 저녁 운영되는 야시장. 먹거리·공예·버스킹 부스 운영.",
    createdAt: "2026-05-18T06:00:00.000Z",
  }),

  // ── 이번 주 예정 ──
  make({
    title: "월미도 여름밤 불꽃축제",
    category: "festival",
    district: "jemulpo",
    startDate: "2026-06-13",
    endDate: "2026-06-13",
    venue: "월미문화의거리",
    organizer: "제물포구",
    host: "제물포구문화재단",
    indoorOutdoor: "outdoor",
    description: "월미도 앞바다를 배경으로 펼쳐지는 여름 불꽃쇼와 야시장.",
    createdAt: "2026-06-03T07:10:00.000Z",
  }),
  make({
    title: "인천 청년 잡페어",
    category: "expo",
    district: "namdong",
    startDate: "2026-06-12",
    endDate: "2026-06-12",
    venue: "남동구청 대강당",
    organizer: "인천광역시",
    host: "인천일자리포털",
    indoorOutdoor: "indoor",
    description:
      "지역 청년 구직자를 위한 채용 박람회. 현장 면접과 직무 상담 부스 운영.",
    websiteUrl: "https://www.incheon.go.kr/job",
    createdAt: "2026-06-05T04:00:00.000Z",
  }),
  make({
    title: "계양산 반딧불이 축제",
    category: "festival",
    district: "gyeyang",
    startDate: "2026-06-13",
    endDate: "2026-06-14",
    venue: "계양산 일원",
    organizer: "계양구",
    host: "계양구청",
    indoorOutdoor: "outdoor",
    description: "초여름 계양산에서 반딧불이를 관찰하는 생태 체험 축제.",
    createdAt: "2026-06-04T08:30:00.000Z",
  }),
  make({
    title: "검단신도시 가족 페스티벌",
    category: "festival",
    district: "geomdan",
    startDate: "2026-06-15",
    endDate: "2026-06-16",
    venue: "검단중앙공원",
    organizer: "검단구",
    host: "검단구청",
    indoorOutdoor: "outdoor",
    description: "검단신도시 주민을 위한 가족 단위 문화·체험 행사.",
    createdAt: "2026-06-06T01:00:00.000Z",
  }),

  // ── 이번 달 예정 ──
  make({
    title: "제물포 개항장 문화재 야행",
    category: "festival",
    district: "jemulpo",
    startDate: "2026-06-19",
    endDate: "2026-06-20",
    venue: "개항장 거리 일원",
    organizer: "제물포구",
    host: "인천문화재단",
    indoorOutdoor: "outdoor",
    description: "개항기 근대건축물을 배경으로 한 야간 문화재 탐방·공연 프로그램.",
    createdAt: "2026-05-29T02:30:00.000Z",
  }),
  make({
    title: "인천 스타트업 네트워킹 데이",
    category: "etc",
    district: "yeonsu",
    startDate: "2026-06-18",
    endDate: "2026-06-18",
    venue: "송도 스타트업파크",
    organizer: "인천창조경제혁신센터",
    host: "인천창조경제혁신센터",
    indoorOutdoor: "indoor",
    description: "지역 창업가와 투자자가 교류하는 네트워킹 행사. IR 피칭 세션 포함.",
    createdAt: "2026-06-06T06:20:00.000Z",
  }),
  make({
    title: "송도 글로벌 푸드 페스티벌",
    category: "festival",
    district: "yeonsu",
    startDate: "2026-06-20",
    endDate: "2026-06-22",
    venue: "송도달빛축제공원",
    organizer: "인천광역시",
    host: "인천관광공사",
    indoorOutdoor: "outdoor",
    description: "세계 각국의 음식과 문화를 소개하는 미식 축제.",
    isFeatured: true,
    likes: 11,
    createdAt: "2026-05-28T08:00:00.000Z",
  }),
  make({
    title: "영종도 을왕리 해변 음악회",
    category: "performance",
    district: "yeongjong",
    startDate: "2026-06-21",
    endDate: "2026-06-21",
    venue: "을왕리해수욕장",
    organizer: "영종구",
    host: "영종국제도시문화원",
    indoorOutdoor: "outdoor",
    description: "노을 지는 을왕리 해변에서 열리는 어쿠스틱 음악회.",
    createdAt: "2026-06-02T09:30:00.000Z",
  }),
  make({
    title: "미추홀 학산문화제",
    category: "performance",
    district: "michuhol",
    startDate: "2026-06-26",
    endDate: "2026-06-27",
    venue: "미추홀구 문학경기장 일원",
    organizer: "미추홀구",
    host: "미추홀문화원",
    indoorOutdoor: "mixed",
    description: "지역 예술단체가 참여하는 미추홀구 대표 종합 문화축제.",
    createdAt: "2026-05-26T04:30:00.000Z",
  }),
  make({
    title: "인천 가족 과학축제",
    category: "education",
    district: "yeonsu",
    startDate: "2026-06-28",
    endDate: "2026-06-29",
    venue: "인천종합문화예술회관",
    organizer: "인천광역시교육청",
    host: "인천교육과학연구원",
    indoorOutdoor: "indoor",
    description: "어린이·청소년 대상 과학 체험 부스와 강연으로 구성된 교육 행사.",
    createdAt: "2026-06-01T03:30:00.000Z",
  }),
  make({
    title: "인천 시민 건강 마라톤 대회",
    category: "sports",
    district: "seo",
    startDate: "2026-06-28",
    endDate: "2026-06-28",
    venue: "인천아시아드주경기장",
    organizer: "인천광역시체육회",
    host: "인천광역시육상연맹",
    indoorOutdoor: "outdoor",
    description: "5km·10km·하프 코스로 진행되는 시민 참여형 마라톤.",
    websiteUrl: "https://www.icsports.or.kr",
    attachmentUrl: "https://www.icsports.or.kr/marathon/guide.pdf",
    createdAt: "2026-05-30T05:30:00.000Z",
  }),

  // ── 이후 예정 ──
  make({
    title: "청라 호수공원 빛 축제",
    category: "festival",
    district: "seo",
    startDate: "2026-07-04",
    endDate: "2026-07-06",
    venue: "청라호수공원",
    organizer: "서해구",
    host: "서해구문화재단",
    indoorOutdoor: "outdoor",
    description: "청라호수공원을 무대로 한 미디어 라이트·분수쇼 야간 축제.",
    createdAt: "2026-05-21T07:00:00.000Z",
  }),
  make({
    title: "영종 하늘도시 드론 라이트쇼",
    category: "etc",
    district: "yeongjong",
    startDate: "2026-07-12",
    endDate: "2026-07-12",
    venue: "영종 하늘도시 중앙공원",
    organizer: "영종구",
    host: "영종국제도시문화원",
    indoorOutdoor: "outdoor",
    description: "수백 대의 드론이 밤하늘을 수놓는 라이트쇼 공연.",
    createdAt: "2026-06-07T02:00:00.000Z",
  }),
  make({
    title: "백령도 심청 효 문화축제",
    category: "festival",
    district: "ongjin",
    startDate: "2026-07-18",
    endDate: "2026-07-19",
    venue: "백령도 심청각 일원",
    organizer: "옹진군",
    host: "옹진군문화원",
    indoorOutdoor: "outdoor",
    description: "심청 설화를 주제로 한 옹진군 백령도의 향토 문화축제.",
    createdAt: "2026-05-14T06:00:00.000Z",
  }),
  make({
    title: "인천 펜타포트 락 페스티벌",
    category: "festival",
    district: "yeonsu",
    startDate: "2026-08-07",
    endDate: "2026-08-09",
    venue: "송도달빛축제공원",
    organizer: "인천광역시",
    host: "인천문화재단",
    indoorOutdoor: "outdoor",
    description:
      "국내 대표 록 페스티벌. 국내외 아티스트가 출연하는 3일간의 음악 축제.",
    websiteUrl: "https://pentaportrock.com",
    isFeatured: true,
    likes: 42,
    createdAt: "2026-05-10T10:00:00.000Z",
  }),
  make({
    title: "인천 비엔날레 미디어아트전",
    category: "expo",
    district: "michuhol",
    startDate: "2026-09-01",
    endDate: "2026-10-31",
    venue: "인천아트플랫폼",
    organizer: "인천문화재단",
    host: "인천아트플랫폼",
    indoorOutdoor: "indoor",
    description: "국내외 작가들의 미디어아트 작품을 두 달간 전시하는 대규모 기획전.",
    isFeatured: true,
    createdAt: "2026-05-18T09:00:00.000Z",
  }),
  make({
    title: "강화 새우젓 축제",
    category: "festival",
    district: "ganghwa",
    startDate: "2026-10-10",
    endDate: "2026-10-19",
    venue: "강화외포리 젓갈수산시장",
    organizer: "강화군",
    host: "강화군수협",
    indoorOutdoor: "outdoor",
    description: "가을 제철 새우젓과 강화 특산물을 즐기는 향토 축제.",
    createdAt: "2026-05-12T07:00:00.000Z",
  }),

  // ── 종료 ──
  make({
    title: "강화 고려산 진달래 축제",
    category: "festival",
    district: "ganghwa",
    startDate: "2026-04-18",
    endDate: "2026-04-26",
    venue: "고려산 일원",
    organizer: "강화군",
    host: "강화군청",
    indoorOutdoor: "outdoor",
    description: "고려산 진달래 군락을 배경으로 한 봄철 산상 축제. (종료)",
    createdAt: "2026-03-10T01:00:00.000Z",
  }),
  make({
    title: "인천대공원 봄꽃 페스티벌",
    category: "festival",
    district: "namdong",
    startDate: "2026-04-12",
    endDate: "2026-04-20",
    venue: "인천대공원",
    organizer: "남동구",
    host: "인천시설공단",
    indoorOutdoor: "outdoor",
    description: "벚꽃·튤립이 어우러진 인천대공원의 봄꽃 축제. (종료)",
    createdAt: "2026-03-12T02:00:00.000Z",
  }),
  make({
    title: "영종도 봄꽃 마라톤",
    category: "sports",
    district: "yeongjong",
    startDate: "2026-04-05",
    endDate: "2026-04-05",
    venue: "영종해안남로 일원",
    organizer: "영종구",
    host: "영종체육회",
    indoorOutdoor: "outdoor",
    description: "벚꽃길을 달리는 봄철 마라톤 대회. (종료)",
    createdAt: "2026-03-01T01:00:00.000Z",
  }),
  make({
    title: "인천교육박람회",
    category: "education",
    district: "yeonsu",
    startDate: "2026-05-15",
    endDate: "2026-05-17",
    venue: "송도컨벤시아",
    organizer: "인천광역시교육청",
    host: "인천교육과학연구원",
    indoorOutdoor: "indoor",
    description: "교육 프로그램·에듀테크 기업이 참가한 교육 박람회. (종료)",
    createdAt: "2026-04-20T02:00:00.000Z",
  }),
  make({
    title: "동인천 개항장 문화축제",
    category: "performance",
    district: "jemulpo",
    startDate: "2026-05-24",
    endDate: "2026-05-25",
    venue: "화도진공원",
    organizer: "제물포구",
    host: "제물포구문화원",
    indoorOutdoor: "outdoor",
    description: "개항기 역사를 주제로 한 거리 공연과 체험 행사. (종료)",
    createdAt: "2026-04-28T04:30:00.000Z",
  }),
  make({
    title: "검단 어울림 음악회",
    category: "performance",
    district: "geomdan",
    startDate: "2026-05-30",
    endDate: "2026-05-31",
    venue: "검단선사박물관 야외마당",
    organizer: "검단구",
    host: "검단구청",
    indoorOutdoor: "outdoor",
    description: "검단 지역 주민과 함께한 봄맞이 야외 음악회. (종료)",
    createdAt: "2026-05-02T03:00:00.000Z",
  }),

  // ── 반복 행사 (매주 특정 요일) ──
  make({
    title: "송도 주말 플리마켓",
    category: "etc",
    district: "yeonsu",
    startDate: "2026-04-04",
    endDate: "2026-10-25",
    recurrenceType: "weekly",
    recurrenceDays: [0, 6], // 매주 주말
    venue: "송도 트리플스트리트 광장",
    organizer: "연수구",
    host: "송도국제도시상인회",
    indoorOutdoor: "outdoor",
    description: "매주 주말 열리는 핸드메이드·빈티지 플리마켓. (4~10월)",
    createdAt: "2026-03-20T05:00:00.000Z",
  }),
  make({
    title: "계양 수요 음악회",
    category: "performance",
    district: "gyeyang",
    startDate: "2026-03-04",
    endDate: "2026-12-30",
    recurrenceType: "weekly",
    recurrenceDays: [3], // 매주 수요일
    venue: "계양문화회관 소공연장",
    organizer: "계양구",
    host: "계양문화회관",
    indoorOutdoor: "indoor",
    description: "매주 수요일 저녁 7시, 지역 음악가들이 꾸미는 상설 음악회.",
    isFeatured: true,
    createdAt: "2026-02-25T06:00:00.000Z",
  }),
  make({
    title: "강화 토요 농부장터",
    category: "festival",
    district: "ganghwa",
    startDate: "2026-05-02",
    endDate: "2026-11-28",
    recurrenceType: "weekly",
    recurrenceDays: [6], // 매주 토요일
    venue: "강화풍물시장 앞마당",
    organizer: "강화군",
    host: "강화군농업기술센터",
    indoorOutdoor: "outdoor",
    description: "매주 토요일 강화 지역 농가가 직접 참여하는 로컬푸드 직거래 장터.",
    createdAt: "2026-04-15T01:00:00.000Z",
  }),
  make({
    title: "부평 금요 야시장",
    category: "etc",
    district: "bupyeong",
    startDate: "2026-05-01",
    endDate: "2026-09-25",
    recurrenceType: "weekly",
    recurrenceDays: [5], // 매주 금요일
    venue: "부평 문화의거리",
    organizer: "부평구",
    host: "부평구상인연합회",
    indoorOutdoor: "outdoor",
    description: "매주 금요일 저녁 먹거리·버스킹이 어우러지는 야시장. (5~9월)",
    createdAt: "2026-04-10T07:00:00.000Z",
  }),
];

// 검토 대기 중인 제보 샘플 (관리자 큐에 표시됨)
export const seedSubmissions: EventSubmission[] = [
  {
    id: "b0000000-0000-4000-8000-000000000001",
    title: "연수구 벚꽃 야간 산책 행사",
    category: "festival",
    startDate: "2026-04-03",
    endDate: "2026-04-05",
    venue: "센트럴파크 산책로",
    district: "yeonsu",
    organizer: null,
    host: null,
    description: "주민 제보: 벚꽃 시즌 야간 조명 산책 행사가 열린다고 합니다.",
    websiteUrl: null,
    reporterName: "김OO",
    reporterContact: "byond1318@gmail.com",
    status: "pending",
    createdAt: "2026-06-09T08:00:00.000Z",
  },
  {
    id: "b0000000-0000-4000-8000-000000000002",
    title: "부평 청소년 댄스 경연대회",
    category: null,
    startDate: "2026-07-05",
    endDate: null,
    venue: "부평아트센터",
    district: "bupyeong",
    organizer: null,
    host: null,
    description: "정확한 일정은 추가 확인 필요. 부평아트센터에서 개최 예정이라고 함.",
    websiteUrl: null,
    reporterName: null,
    reporterContact: null,
    status: "pending",
    createdAt: "2026-06-08T05:30:00.000Z",
  },
];
